parameters:

services:
    meup.demo.center_manager:
        class: Meup\DemoBundle\Manager\CenterManager
        arguments: ['@security.secure_random', '%kernel.cache_dir%']
    twig.extension.meup.demo:
        class: Meup\DemoBundle\Twig\Extension\DemoExtension
        public: false
        tags:
            - { name: twig.extension }
        arguments: ['@twig.loader']
    meup.demo.listener:
        class: Meup\DemoBundle\EventListener\ControllerListener
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
        arguments: ['@twig.extension.meup.demo']
