imports:
    - { resource: config.yml }

framework:
    router:   { resource: "%kernel.root_dir%/config/routing_dev.yml" }
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug
        firephp:
            type:  firephp
            level: info
        chromephp:
            type:  chromephp
            level: info

assetic:
    use_controller: true

#swiftmailer:
#    delivery_address: me@example.com

# Nelmio API Doc
nelmio_api_doc:
    name: API Documentation
    request_listener:
        enabled: false
    sandbox:
        enabled: true
        body_format: json
        authentication:
            name: Authorization
            delivery: header
            type: bearer
        request_format:
            formats:
                json: application/json
                xml: application/xml
                html: text/html
            method: format_param
            default_format: json