home:
    pattern: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /doc
        permanent: true

meup_api:
    resource: "@MeupApiBundle/Resources/config/routing.yml"
    prefix:   /api

NelmioApiDocBundle:
  resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
  prefix:   /doc

NelmioSwagger:
  resource: "@NelmioApiDocBundle/Resources/config/swagger_routing.yml"
  prefix:   /swagger

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"