security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_API:         ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN]

    providers:
        in_memory:
            memory:
                users:
                    restapi:  { password: secretpw, roles: [ 'ROLE_API' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        oauth_token:
            pattern:    ^/oauth/v2/token
            security:   false

        oauth_authorize:
            pattern:    ^/oauth/v2/auth
            security:   false

        apidemo:
            pattern:    ^/demo
            anonymous:  ~
            stateless:  true
            http_basic:
                realm:  "Demo REST API (username: restapi, password: secretpw)"

        api:
            pattern:    ^/api
            fos_oauth:  true
            stateless:  true
            anonymous:  false # can be omitted as its default value

        ui:
            pattern:    ^/ui
            security:   false

    access_control:
        - { path: ^/swagger, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/demo,    role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/,        role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api,     role: IS_AUTHENTICATED_FULLY }