parameters:
#    meup_ui.example.class: Meup\Bundle\UIBundle\Example

services:
#    meup_ui.example:
#        class: %meup_ui.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
