Meup\Bundle\ApiBundle\Entity\Sku:
    type: entity
    table: sku_registry
    fields:
        id:
            type: string
            id: true
            generator:
                strategy: AUTO
        code:
            type: string
            nullable: false
        project:
            type: string
            nullable: false
        foreignType:
            type: string
            nullable: false
            column: foreign_type
        foreignId:
            type: string
            nullable: false
            column: foreign_id
        createdAt:
            type: datetime
            nullable: false
            column: created_at
        deletedAt:
            type: datetime
            nullable: true
            column: deleted_at
        permalink:
            type: string
            nullable: true