Meup\Bundle\ApiBundle\Entity\Sku:
    type: entity
    table: Sku_Registry

    fields:
        id:
            type: string
            id: true
            generator:
                strategy: AUTO
        code:
            type: string
            nullable: false
        project:
            type: string
            nullable: false
            length: 100
        foreign_type:
            type: string
            nullable: false
        foreign_id:
            type: string
            nullable: false
        createdAt:
            type: datetime
            nullable: false
        deletedAt:
            type: datetime
            nullable: true

