Meup\Bundle\ApiBundle\Entity\Sku:
  exclusion_policy: ALL
  read_only: false
  accessor_order: alphabetical

  properties:
    createdAt:
      expose: true
      type: DateTime
      serialized_name: created_at
    deletedAt:
      type: DateTime
      serialized_name: deleted_at
  virtual_properties:
    isActive:
      expose: true
      type: boolean
      serialized_name: active