# get sku details
meup_api_get_sku:
    pattern: /{sku}.{_format}
    defaults: { _controller: MeupApiBundle:Sku:getSku, _format: json }
    requirements:
        _method: GET
        sku:     "[\d\w]*"
        _format: json

# create a new sku
meup_api_post_sku:
    pattern: /
    defaults: { _controller: MeupApiBundle:Sku:postSku, _format: json }
    requirements:
        _method: POST

# delete sku
meup_api_delete_sku:
    pattern: /
    defaults: { _controller: MeupApiBundle:Sku:deleteSku, _format: json }
    requirements:
        _method: DELETE