# get sku details
meup_api_get_sku:
    pattern: /{sku}.{_format}
    defaults: { _controller: MeupApiBundle:Sku:getSku, _format: json }
    requirements:
        _method: GET
        sku:     "[\d\w]*"
        _format: json

# create a new sku
meup_api_post_sku:
    pattern: /
    defaults: { _controller: MeupApiBundle:Sku:postSku, _format: json }
    requirements:
        _method: POST

# allocate a new sku
meup_api_allocate_sku:
    pattern: /{project}
    defaults: { _controller: MeupApiBundle:Sku:allocateSku, _format: json }
    requirements:
        _method: POST

# edit an sku
meup_api_edit_sku:
    pattern: /{sku}.{_format}
    defaults: { _controller: MeupApiBundle:Sku:putSku, _format: json }
    requirements:
        _method: PUT
        sku:     "[\d\w]*"
        _format: json

# delete sku
meup_api_delete_sku:
    pattern: /{sku}
    defaults: { _controller: MeupApiBundle:Sku:deleteSku }
    requirements:
        _method: DELETE
        sku:     "[\d\w]*"

# disable sku
meup_api_disable_sku:
    pattern: /disable/{sku}
    defaults: { _controller: MeupApiBundle:Sku:disableSku }
    requirements:
        _method: PUT
        sku:     "[\d\w]*"
