parameters:
    meup_kali.sku_model.class:     Meup\Bundle\ApiBundle\Model\Sku
    meup_kali.sku_factory.class:   Meup\Bundle\ApiBundle\Factory\SkuFactory
    meup_kali.sku_generator.class: Meup\Bundle\ApiBundle\Service\SkuGenerator
    meup_kali.sku_form_type.class: Meup\Bundle\ApiBundle\Form\Type\SkuType

services:
    meup_kali.sku_factory:
        class: %meup_kali.sku_factory.class%
        arguments:
            - %meup_kali.sku_model.class%

    meup_kali.sku_generator:
        class: %meup_kali.sku_generator.class%
        arguments:
            - %default_sku_code_length%

    meup_kali.sku_form.sku:
        class: meup_kali.sku_form_type.class
        tags:
            - { name: form.type, alias: sku }
