parameters:
    meup_kali.sku.manager: Meup\Bundle\ApiBundle\Manager\SkuManager
    meup_kali.sku.entity.class: Meup\Bundle\ApiBundle\Entity\Sku

services:
    meup_kali.sku_manager:
        class: %meup_kali.sku.manager%
        arguments:
            - @doctrine.orm.entity_manager
            - %meup_kali.sku.entity.class%
