services:
    meup_kali.sku_factory:
        class: Meup\Bundle\ApiBundle\Factory\SkuFactory
        arguments:
            - Meup\Bundle\ApiBundle\Entity\Sku

    meup_kali.sku_form_type:
        class: Meup\Bundle\ApiBundle\Form\SkuType
        arguments:
            - @meup_kali.sku_factory
            - @meup_kali.sku_manager
        tags:
            - { name: form.type, alias: sku }

    meup_kali.sku_generator:
        class: Meup\Bundle\ApiBundle\Service\CodeGenerator
        arguments:
            - %default_sku_code_length%
            - %default_sku_code_alphabet%

    meup_kali.sku_manager:
        class: Meup\Bundle\ApiBundle\Manager\SkuManager
        arguments:
            - @meup_kali.sku_repository
            - @meup_kali.sku_factory
            - @meup_kali.sku_generator

    meup_kali.purge_command:
        class: Meup\Bundle\ApiBundle\Command\PurgeCommand
        tags:
            -  { name: console.command }
        arguments:
            - @meup_kali.sku_manager

    meup_kali.sku_repository:
        class: Meup\Bundle\ApiBundle\Doctrine\SkuRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - Meup\Bundle\ApiBundle\Entity\Sku