parameters:
    meup_kali.sku_model.class:   Meup\Bundle\ApiBundle\Model\Sku
    meup_kali.sku_factory.class: Meup\Bundle\ApiBundle\Factory\SkuFactory

services:
    meup_kali.sku_factory:
        class: %meup_kali.sku_factory.class%
        arguments:
            - %meup_kali.sku_model.class%