Meup\Bundle\ApiBundle\Model\Sku:
    properties:
        project:
            - NotBlank: ~
            - NotNull: ~
        foreignType:
            - NotBlank: ~
            - NotNull: ~
        foreignId:
            - NotBlank: ~
            - NotNull: ~